- hosts: localhost
  become: true

  # vars:
  #   is_mac: which apt
  #   is_ubuntu: which apt

  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present

  tasks:
    - include: tasks/dotfiles.yml
    # - include: tasks/cargo-packages.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/fonts.yml
